# Generated by Django 2.2.4 on 2019-08-22 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recivere_id', models.IntegerField()),
                ('recivere_type', models.IntegerField(choices=[(1, 'Chatroom'), (2, 'User')], default=1)),
                ('message', models.TextField()),
                ('message_type', models.IntegerField(choices=[(1, 'Text'), (2, 'File')], default=1)),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('seen_datetime', models.DateTimeField(null=True)),
                ('is_reply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Messages')),
                ('sender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='MessageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='messagefiles/')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.Messages')),
            ],
        ),
        migrations.CreateModel(
            name='Chatrooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_deleted', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_name='users', to='chat.Profiles')),
            ],
        ),
    ]
