# Generated by Django 2.2.4 on 2019-08-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190826_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='chat.Profiles'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
