# Generated by Django 2.2.4 on 2019-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190829_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='recievere_type',
            new_name='reciever_type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recievere_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='reciever_id',
            field=models.CharField(default='vahid', max_length=40),
            preserve_default=False,
        ),
    ]
